### ISSUE TITLE
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "" (SQL: select count(*) as aggregate from "admins" where "email" = test@admin.com and "id" <> )

### ISSUE THREAD

**Issue by TeLoardBruh** [bitfumes/laravel-multiauth#114]
its working well, with mysql locally, but when host to heroku and use postgres this pop up when i create new [admin[](url)](url)

**Comment by davecardwell** [comment]
We’re experiencing this too. Looks like the same issue as #86 which was closed. @sarthaksavvy - had you found a solution?

I believe the issue is here: https://github.com/bitfumes/laravel-multiauth/blob/master/src/Http/Requests/AdminRequest.php#L31

When creating a new admin the value of `request('admin.id')` is `NULL`, making the rule `"required|email|max:255|unique:admins,email,"`. The ORM is passing that ID column check as an empty string, which PostgreSQL won’t coalesce into an integer like MySQL does.
