### ISSUE TITLE
Database migration problem.

### ISSUE THREAD

**Issue by mehedi432** [bitfumes/laravel-multiauth#93]
In laravel 7 i got some errors about
```sh
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `permissions` add index `permissions_name_index`(`name`))
```
I also change
```php 
Schema::defaultStringLength(191);
```
but still getting the same error
Can you or any one help me...

**Comment by sarthaksavvy** [comment]
Thanks for this update, 
I should add this to docs.

Refer this article: https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by pwilson77** [comment]
I still had the issue even after implementing the articles recommended changes.

I fixed by following the instructions in this [thread](https://github.com/laravel/framework/issues/27806#issuecomment-470745850).

It involves changing the mysql settings in `config/database.php` you have to change 
`charset` to `utf8` and the `collation` to `utf8_general_ci`

Hope this helps

**Comment by sarthaksavvy** [comment]
Please follow this 
Refer this article: https://laravel-news.com/laravel-5-4-key-too-long-error

If this doesn't help, please share the screenshot of error
